### ISSUE TITLE
Introduce the interest rate chart to summary section

### ISSUE THREAD

**Issue by danielfireman** [danielfireman/isumm#2]
This chart will have a month-by-month interest rate accross **all** investments. It should consider deposits and withdrawals based on what isumm.Operations.Summarize returns (balance and changes). The formula for calculating the interest rate of month i goes as follows.

I<sub>i,i-1</sub> = (B<sub>i</sub> - (B<sub>i-1</sub> + C<sub>i-1</sub>)) /  ((B<sub>i-1</sub> + C<sub>i-1</sub>)))

Where I is the interest rate from I is the interest rate, B the balance and  and C the change.

It is fine to share the amount summary chat's look-and-feel.

**Comment by IdNotFound** [comment]
Should we subtract C_i as well, to prevent deposits and withdrawals in the current month from impacting the interest rate? Unit tests will definitely help here :)

**Comment by danielfireman** [comment]
I would say no, but maybe it seems that we should improve documentation.

From Readme.md:

Withdrawal and Deposit: used to calculate month-by-month profit.
Balance: for the sake of simplification, only one is considered per month. If you added more than one balance operations, only the most-recent is used.

What I meant is that balance is already the end-of-the-month balance. This means that all deposits and withdrawals are already accounted as well as daily interested and all that (i.e. when the first deposit occurs in the middle of the month). The rationale is to leave the to the bank the hard work.

What do you think?

**Comment by danielfireman** [comment]
Actually, you're correct.

The formula seems to be 

Ii,i-1 = (B<sub>i</sub> - (B<sub>i-1</sub> + C<sub>i</sub>)) / ((B<sub>i-1</sub> + C<sub>i</sub>)))

And yeah, unit tests FTW
