### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by danielfireman** [danielfireman/isumm#26]

**Comment by IdNotFound** [comment]
Found these, ready to use:
http://www.freefavicon.com/freefavicons/business/iconinfo/dollar-signs-152-184803.html
http://www.freefavicon.com/freefavicons/business/iconinfo/money-3-152-167778.html

Also, found instructions on how to reference them in HTML here:
http://www.favicon-generator.org/

Copy & paste of instructions:
"""
USING A FAVICON
After generating a favicon with this tool download and save to the root directory of your site. Then include the following code in the head of your HTML document.

``` html
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
<link rel="icon" href="/favicon.ico" type="image/x-icon">
```

"""
