### ISSUE TITLE
Implement a simple registry of isumm instances

### ISSUE THREAD

**Issue by danielfireman** [danielfireman/isumm#31]
Just for us to know how many instances we have running. It could issue a fire-and-forget request at init().

**Comment by IdNotFound** [comment]
Cool idea! :D

**Comment by danielfireman** [comment]
Registry is already up an running at isumm-registry.appspot.com

Pretty symple form + UserAgent API (following appengine urlfetcher service). Repository can be found at: https://github.com/danielfireman/isumm-registry
