### ISSUE TITLE
Date is not showing up correctly in graphs

### ISSUE THREAD

**Issue by danielfireman** [danielfireman/isumm#35]
As one can see bellow, if your monitoring your investiments for quite a long time, you won't be able to read the dates. 

A quick solution is to show only the lat 12 months. Then we could have feature request to show a lifelong graph. This graph won't have X axis.

![isumm_graphic](https://cloud.githubusercontent.com/assets/8951363/15724517/bf6953f6-281d-11e6-8ebe-956571cd7870.png)

**Comment by danielfireman** [comment]
Solved in a simple way with https://github.com/danielfireman/isumm/commit/f33b93214b445355dccef873aac6c0d447122f1a

![isumm danielfireman appspot com app](https://cloud.githubusercontent.com/assets/8951363/16436371/b9384080-3d73-11e6-97d7-37adc8d9a317.png)

**Comment by marcorosner** [comment]
What are you think of use the 5 points instead 3? I think this would help to identify a particular month more easily.
