### ISSUE TITLE
Too many decimal places

### ISSUE THREAD

**Issue by brunojdo** [danielfireman/isumm#39]
Would be better to visualization if the chart shows just two decimal places. 
![captura de tela 2016-06-26 as 17 33 03](https://cloud.githubusercontent.com/assets/8000984/16364712/5a458002-3bc4-11e6-919b-ea32f8ce78df.png)

**Comment by danielfireman** [comment]
http://stackoverflow.com/questions/11698438/flot-chart-unwanted-decimals-on-changing-width

TL;DR; tickeDecimals: 0

**Comment by danielfireman** [comment]
http://www.w3schools.com/jsref/jsref_tofixed.asp

Sending the fix.
