### ISSUE TITLE
Data format is not appear on Firefox

### ISSUE THREAD

**Issue by marcorosner** [danielfireman/isumm#40]
Data format is only available on Chrome browser

**Comment by danielfireman** [comment]
http://stackoverflow.com/questions/22983013/how-to-get-html-5-input-type-date-working-in-firefox-and-or-ie-10

Look at answer number 6

https://jqueryui.com/datepicker/

**Comment by marcorosner** [comment]
When the date has submitted this message appears: "Invalid operation date: 21/06/2016". @danielfireman, this format is not accepted by the isumm backend?

**Comment by danielfireman** [comment]
@marcorosner nope, it is not. The backend does not understands format, it only knows one format. If we chose to format on the FE, we must convert back to the BE format before send. 

Please take a look at what I've done in commit f6952961856c70229d410366893aa555da56ee74

**Comment by danielfireman** [comment]
I believe @brunodias20 fixed this one. Lets remember that firefox is not our target, so breakages on firefox are not going to be prioritized.

**Comment by marcorosner** [comment]
Its not related to Firefox, is related to portuguese date format.

**Comment by danielfireman** [comment]
This has also been fixed. Bellow you can see a screenshot from isumm-demo.appspot.com
![isumm demo appspot com app](https://cloud.githubusercontent.com/assets/8951363/16472704/898131ac-3e3c-11e6-9879-196f6d6257ff.png)
