### ISSUE TITLE
Consolidate Lang and Money Format 

### ISSUE THREAD

**Issue by danielfireman** [danielfireman/isumm#45]
Currently we have Language English, Number format in US and Currency in R$.

The funniest thing is that we only have pt-BR users.

Time to consolidate. Lets have everything in pt-BR then we add internationalization afterwards.

Marking as a bug just because I think it is bugged UI. No strong feelings here.

**Comment by brunojdo** [comment]
@danielfireman if you like to see the refactoring, click [here](http://isumm-canary.appspot.com/app)

**Comment by danielfireman** [comment]
The input still using "." instead of "," to separate decimal places.

**Comment by marcorosner** [comment]
The words is not translated:

"05/2016: Saldo:R$ ... :: Aportes-Saques:-R$ ...
 31/05/2016 Balance R$ ...
 23/05/2016 Withdrawal R$ ...
 10/05/2016 Deposit R$ ..."
